import React, { useState } from 'react';
import { TrendingUp, Heart } from 'lucide-react';

interface StatCardProps {
  title: string;
  value: string;
  subtitle?: string;
  trend?: string;
  trendPercent?: string;
  variant?: 'default' | 'blue' | 'light' | 'gradient';
}

const StatCard: React.FC<StatCardProps> = ({ title, value, subtitle, trend, trendPercent, variant = 'default' }) => {
  const getVariantStyles = () => {
    switch (variant) {
      case 'blue':
        return 'bg-[#157bff] text-white';
      case 'light':
        return 'bg-gray-50 text-gray-800';
      case 'gradient':
        return 'bg-gradient-to-r from-yellow-400 via-gray-600 to-[#157bff] text-white';
      default:
        return 'bg-[#157bff]/80 text-white';
    }
  };

  return (
    <div className={`rounded-lg p-6 ${getVariantStyles()}`}>
      <h3 className="text-sm font-semibold uppercase tracking-wide opacity-80 mb-4">
        {title}
      </h3>
      <div className="text-4xl font-bold mb-2">{value}</div>
      {subtitle && <p className="text-sm opacity-70 mb-3">{subtitle}</p>}
      {trend && (
        <div className="flex items-center gap-1 text-green-400">
          <TrendingUp size={16} />
          <span className="text-sm font-semibold">{trend}</span>
        </div>
      )}
      {trendPercent && (
        <div className="text-xs opacity-70 mt-1">YOY: {trendPercent}</div>
      )}
    </div>
  );
};

const CustomerSatisfactionCard = () => {
  return (
    <div className="bg-gray-50 rounded-lg p-8 flex flex-col items-center justify-center">
      <div className="bg-yellow-400 rounded-full p-4 mb-4">
        <Heart size={32} className="text-white" />
      </div>
      <h3 className="text-[#157bff] font-semibold mb-4">Customer Satisfaction</h3>
      <div className="text-center mb-6">
        <div className="text-3xl font-bold text-[#157bff] mb-1">23K</div>
        <p className="text-sm text-gray-600">Users</p>
      </div>
      <div className="text-center">
        <div className="text-3xl font-bold text-[#157bff] mb-1">$54M+</div>
        <p className="text-sm text-gray-600">Transaction</p>
      </div>
    </div>
  );
};

const AffiliateNetworkCard = () => {
  return (
    <div className="bg-[#157bff] text-white rounded-lg p-6">
      <h3 className="text-lg font-semibold mb-6 text-center">Affiliate Network</h3>
      
      <div className="space-y-6">
        <div className="pb-6 border-b border-blue-700">
          <p className="text-sm opacity-70 mb-2">AFFILIATES</p>
          <div className="flex justify-between items-center">
            <div className="text-3xl font-bold">1M+</div>
            <div className="text-green-400 text-sm font-semibold">↑ YOY: 31.89%</div>
          </div>
        </div>

        <div className="pb-6 border-b border-blue-700">
          <p className="text-sm opacity-70 mb-2">PRODUCTS LISTED</p>
          <div className="flex justify-between items-center">
            <div className="text-3xl font-bold">779k+</div>
            <div className="text-green-400 text-sm font-semibold">↑ YOY: 19.9%</div>
          </div>
        </div>

        <div className="pb-6 border-b border-blue-700">
          <p className="text-sm opacity-70 mb-2">PAID TO AFFILIATES</p>
          <div className="flex justify-between items-center">
            <div className="text-3xl font-bold">$1.5M+</div>
            <div className="text-green-400 text-sm font-semibold">↑ YOY: 21.89%</div>
          </div>
        </div>

        <div>
          <p className="text-sm opacity-70 mb-2">SALES GENERATED BY AFFILIATE</p>
          <div className="flex justify-between items-center">
            <div className="text-3xl font-bold">779k+</div>
            <div className="text-green-400 text-sm font-semibold">↑ YOY: 19.9%</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default function Dashboard() {
  return (
    <div className="">
      <div className="w-full">
        <h1 className="text-4xl font-semibold text-gray-900 mb-8">Dashboard</h1>

        {/* Hero Card */}
        <div className="mb-8">
          <StatCard
            title="Paid to Creators"
            value="$9,000+"
            trend="↑ 19.82%"
            variant="gradient"
          />
        </div>

        {/* Top Row - Main Stats */}
        <div className="grid grid-cols-3 gap-6 mb-8">
          <StatCard
            title="Transactions"
            value="629K"
            trend="↑ YOY: 55.73%"
            variant="blue"
          />
          <StatCard
            title="Creators"
            value="241K"
            trend="↑ YOY: 60.78%"
            variant="blue"
          />
          <StatCard
            title="Registered Users"
            value="1.5M+"
            trend="↑ YOY: 32.3%"
            variant="blue"
          />
        </div>

        {/* Middle Row - Secondary Stats */}
        <div className="grid grid-cols-3 gap-6 mb-8">
          <StatCard
            title="Countries"
            value="194"
            variant="light"
          />
          <StatCard
            title="Currencies"
            value="13"
            variant="light"
          />
          <StatCard
            title="Store Views"
            value="44M+"
            trend="↑ YOY: 344.02%"
            variant="light"
          />
        </div>

        {/* Bottom Row - Featured Cards */}
        <div className="grid grid-cols-3 gap-6">
          <div>
            <CustomerSatisfactionCard />
          </div>
          <div className="col-span-2">
            <AffiliateNetworkCard />
          </div>
        </div>
      </div>
    </div>
  );
}